CREATE TABLE `tasks` (
  `task_id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `parent_id` int DEFAULT NULL,
  `assigned_user_id` varchar(50) DEFAULT NULL,
  `sub_completed` int NOT NULL DEFAULT '0',
  `sub_total` int NOT NULL DEFAULT '0',
  `submit_flg` tinyint(1) NOT NULL DEFAULT '0',
  `completed_flg` tinyint(1) NOT NULL DEFAULT '0',
  `connect_flg` tinyint(1) NOT NULL DEFAULT '0',
  `priority` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '1:なし\n2:早急\n3:重要\n4:緊急',
  `deadline` datetime DEFAULT NULL,
  `project_id` varchar(50) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `completed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`task_id`),
  KEY `assigned_user_id_idx` (`assigned_user_id`),
  KEY `project_id_idx` (`project_id`) /*!80000 INVISIBLE */,
  KEY `idx_parent_id` (`parent_id`),
  CONSTRAINT `assigned_user_id` FOREIGN KEY (`assigned_user_id`) REFERENCES `users` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `tasks.project_id` FOREIGN KEY (`project_id`) REFERENCES `projects` (`project_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=187 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci